- name: Destroy AAP on a Proxmox server
  hosts: aap_host
  gather_facts: false
  vars_files:
    - vaults/all.yml
  tasks:

    - name: Run roles/gather-tfstate
      ansible.builtin.include_role:
        name: gather-tfstate

    - name: Unregister hosts with RHN
      community.general.redhat_subscription:
        state: absent
        username: "{{ rhn_user }}"
        password: "{{ rhn_pass }}"
      vars:
        ansible_host: "{{ host_ip }}"
      become: true

    - name: Remove DHCP reservation and DNS entry
      community.routeros.command:
        commands:
          - /ip dhcp-server lease remove [find where address={{ host_ip }}]
          - /ip dns static remove [find where name={{ inventory_hostname }}]
          - /ip dns static remove [find where name={{ inventory_hostname }}.{{ domain }}]
      delegate_to: mtik-router
      vars:
        ansible_user: "{{ router.ansible_user }}"
        ansible_ssh_pass: "{{ router.ansible_ssh_pass }}"

    - name: Run localhost based tasks # noqa: run-once[task]
      delegate_to: localhost
      run_once: true
      block:

        - name: Run roles/setup-localhost
          ansible.builtin.include_role:
            name: setup-localhost

        - name: Run roles/destroy-terraform
          ansible.builtin.include_role:
            name: destroy-terraform
