FROM docker.io/redhat/ubi9:latest

RUN dnf update -y &&\
    dnf install -y python3 python3-pip git &&\
    dnf clean all

RUN pip install --no-cache-dir ansible ansible-lint

RUN dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo &&\
    dnf install -y terraform &&\
    dnf clean all